# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    always_use_package_imports: true
    empty_statements: true
    hash_and_equals: true
    collection_methods_unrelated_type: true
    use_key_in_widget_constructors: true
    valid_regexps: true
    always_declare_return_types: true
    await_only_futures: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    no_default_cases: true
    parameter_assignments: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    require_trailing_commas: true
    always_put_control_body_on_new_line: true
    annotate_overrides: true
    directives_ordering: true
    null_check_on_nullable_type_parameter: true
    package_names: true
    package_prefixed_library_names: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_library_directive: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    avoid_print: false

  analyzer:

    errors:
      missing_required_param: error
      missing_return: error
      invalid_assignment: warning
      invalid_annotation_target: ignore
