// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7sEfqpobL-SVbNt9us5hwVDaiWlDu8S8',
    appId: '1:705969233842:web:227313f27261e12a024eab',
    messagingSenderId: '705969233842',
    projectId: 'cartify-2d918',
    authDomain: 'cartify-2d918.firebaseapp.com',
    storageBucket: 'cartify-2d918.firebasestorage.app',
    measurementId: 'G-X6YGD2W79T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgExtTd6bBdZpMX8fwgrA0NAKfTO0W86Y',
    appId: '1:705969233842:android:15934d231b1d62ec024eab',
    messagingSenderId: '705969233842',
    projectId: 'cartify-2d918',
    storageBucket: 'cartify-2d918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc0_6oOnoanaVB1XxltWZ-HBU4KgaW1tw',
    appId: '1:705969233842:ios:b7b059e1e5e88b80024eab',
    messagingSenderId: '705969233842',
    projectId: 'cartify-2d918',
    storageBucket: 'cartify-2d918.firebasestorage.app',
    iosBundleId: 'com.example.mainCartify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc0_6oOnoanaVB1XxltWZ-HBU4KgaW1tw',
    appId: '1:705969233842:ios:b7b059e1e5e88b80024eab',
    messagingSenderId: '705969233842',
    projectId: 'cartify-2d918',
    storageBucket: 'cartify-2d918.firebasestorage.app',
    iosBundleId: 'com.example.mainCartify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7sEfqpobL-SVbNt9us5hwVDaiWlDu8S8',
    appId: '1:705969233842:web:5d030d3caf2374d5024eab',
    messagingSenderId: '705969233842',
    projectId: 'cartify-2d918',
    authDomain: 'cartify-2d918.firebaseapp.com',
    storageBucket: 'cartify-2d918.firebasestorage.app',
    measurementId: 'G-DBBGHRHVXK',
  );
}
